### ISSUE TITLE
It doesn't work in Chrome

### ISSUE THREAD

**Issue by navakelvin** [greenstorm5417/Vim-For-Docs#4]
Problem:
It only works the displacement and change of mode, the other functions do not work.

**Comment by greenstorm5417** [comment]
Can you be more specific about what doesn't work?

**Comment by navakelvin** [comment]
If you try to make "dd", the entire line is selected but the elimination of the line does not occur. The same goes for all the diw, dw, db, x, vd options, only the selection occurs and does not eliminate.

That is, no Vim action works, only the movements j k l gg G works.

In the other hand, can you implement an option to disable the line numbers? sometimes it can be laggy

**Comment by greenstorm5417** [comment]
should be fixed now, new version dropping soon

**Comment by navakelvin** [comment]
I saw you did an update. It still does not work.

Chrome 135.0.7049.85 (Build oficial) (64 bits)
Windows 10 64 Bits

**Comment by greenstorm5417** [comment]
there is an option to disable the line numbers, if you simply click on the extension icon, there is an option called show line numbers, as for your other issue im still looking into it

**Comment by greenstorm5417** [comment]
I can't seem to re-create your issue, and I've ruled out a performance issue, as it doesn't happen when I slow down my CPU by 20x. try installing the extension on edge(eww) temporarily and see if you're still getting the same issue

**Comment by greenstorm5417** [comment]
I might have spotted the issue. Is your browser in English or Spanish?

**Comment by navakelvin** [comment]
Spanish!

**Comment by greenstorm5417** [comment]
OK I've got a fix coming out for you in the hour!!!! i figured out the issue

**Comment by greenstorm5417** [comment]
its submitted to chrome websore, new version should be out within 24 hours

**Comment by navakelvin** [comment]
Sorry, I don't think it's a language issue. I installed version 1.8 from GitHub and it still doesn't work. In fact, I changed my language to English and tried both version 1.8 and the previous version from the Store, and they don't work. I press dd and the entire line is selected, but it doesn't delete.

**Comment by greenstorm5417** [comment]
I have no idea. Are you getting any errors when you manually install and run it?

**Comment by greenstorm5417** [comment]
@navakelvin, it should be fixed now. Originally, it was a language issue, but then my fix broke it. This final version will work. I re-created the issue from 1.8 and fixed it.

**Comment by navakelvin** [comment]
Good news! It now deletes the line, thx bro. Bugs I've noticed now:

- dd should delete the paragraph, not just the line. In the same sense, "A" should send the editing cursor to the end of the paragraph, not the end of the line. Perhaps you could make this a drop-down menu option like the theme selection menu, something like: Operation mode: Lines or paragraph.
- d doesn't work in linear visual (V) or visual (v) mode.
- x doesn't work in linear visual (V) or visual (v) mode.
- s should delete the selected word or line and enter edit mode.
 
Thank you for your work. These are just ideas.

**Comment by greenstorm5417** [comment]
These are the keybinds I followed https://vim.rtorr.com

**Comment by greenstorm5417** [comment]
These are the keybinds I followed https://vim.rtorr.com

**Comment by greenstorm5417** [comment]
As for d and x, I'll fix that
